table financials
	lineageTag: a02ad5b5-606d-4e93-910e-f7a88706dd87

	column Segment
		dataType: string
		lineageTag: 1b02e834-2a68-4cff-83e8-de73cea551ff
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a138f726-f056-40f5-9d69-baa149166583
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 899107f3-6523-4da3-8662-688de6476652
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: 3d5dbaed-81cb-42df-aa2d-df30f6c4fdec
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: aeff8b3f-da91-4611-b7f6-eb49d9af8889
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: dc327717-7bf3-4d28-8747-c9bb9a08677b
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: f97b5d20-4a99-4cb6-907e-c83ff2056b92
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: dcc23108-2890-4de5-9bbe-75b5a55c6377
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: int64
		formatString: 0
		lineageTag: e7a4cc50-77e9-4c02-896d-799846ff6afc
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 66020c7f-c4c7-4986-8ad0-8049e8819ec5
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: int64
		formatString: 0
		lineageTag: d3d80034-31a6-48f5-bdd4-598d3b2de90f
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		lineageTag: 546c9b5a-6d9d-4e0e-ad16-768ec34da786
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e1e7a63b-1857-4c93-a381-df0c5d298e56
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 1941068e-6b6c-45c2-97be-70ed57035728
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 1dd4e938-0eca-421d-9fbb-49059d8a7c53
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 1260b365-0f11-4cac-8574-07ce40f40b9d
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				  Source = SharePoint.Files(
				    "https://ksoszka-my.sharepoint.com/personal/kamil_soszka_ksoszka_onmicrosoft_com"
				  ),
				  #"https://ksoszka-my sharepoint com/personal/kamil_soszka_ksoszka_onmicrosoft_com/Documents/Kamil Soszka Business Intelligence/financials/docs/_Financial_Sample xlsx"
				    = Source
				    {
				      [
				        #"Folder Path"
				          = "https://ksoszka-my.sharepoint.com/personal/kamil_soszka_ksoszka_onmicrosoft_com/Documents/Kamil Soszka Business Intelligence/financials/docs/",
				        Name = "Financial_Sample.xlsx"
				      ]
				    }
				    [Content],
				  #"Imported Excel Workbook" = Excel.Workbook(
				    #"https://ksoszka-my sharepoint com/personal/kamil_soszka_ksoszka_onmicrosoft_com/Documents/Kamil Soszka Business Intelligence/financials/docs/_Financial_Sample xlsx"
				  ),
				  financials_Table = #"Imported Excel Workbook"{[Item = "financials", Kind = "Table"]}[Data],
				  #"Changed Type" = Table.TransformColumnTypes(
				    financials_Table,
				    {
				      {"Segment", type text},
				      {"Country", type text},
				      {"Product", type text},
				      {"Discount Band", type text},
				      {"Units Sold", type number},
				      {"Manufacturing Price", Int64.Type},
				      {"Sale Price", Int64.Type},
				      {"Gross Sales", type number},
				      {"Discounts", Int64.Type},
				      {"Sales", type number},
				      {"COGS", Int64.Type},
				      {"Profit", type number},
				      {"Date", type date},
				      {"Month Number", Int64.Type},
				      {"Month Name", type text},
				      {"Year", Int64.Type}
				    }
				  )
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

