table Model_Measures
	lineageTag: 7ced52b1-35a9-4956-ab62-2cf13788cb7d

	measure Sales =
			
			/*
			    Business Goal: Establishes a base aggregate measure for the total Sales
			    by summing the values from the 'financials[Sales]' column.
			    This is a fundamental metric that serves as the foundation for further
			    analytical calculations, KPIs, comparative analysis, and business intelligence
			    throughout the entire reporting solution.
			
			    Function Explanation:
			    SUM: A basic aggregation function that returns the sum of all the numbers
			    in the specified column. It operates within the current filter context,
			    meaning it will automatically adjust based on any filters, slicers, or
			    visual context applied in the report.
			
			    This measure is typically used as:
			    - A standalone KPI for overall sales performance
			    - A base for time intelligence calculations (YoY, MTD, QTD, YTD)
			    - A numerator or denominator in ratio calculations (margins, percentages)
			    - A core metric for conditional formatting and various visualizations
			    - A foundation for more complex sales analytics and trend analysis
			*/
			SUM ( financials[Sales] )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: sales
		lineageTag: 44ff6549-362e-429d-9411-61ae5fb8a65c

	measure COGS = ```
			
			/*
			    Business Goal: Establishes a base aggregate measure for the total Cost of Goods Sold (COGS)
			    by summing the values from the 'financials[COGS]' column.
			    This is a fundamental metric for further calculations and analysis.
			    
			    Function Explanation:
			    SUM: A basic aggregation function that returns the sum of all the numbers
			    in the specified column. It operates within the current filter context.
			*/
			SUM ( financials[COGS] )
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: cogs
		lineageTag: 311a5155-9916-4225-9540-2ddfe7900e10

	measure 'Sales KPI Optimized' = ```
			
			/*
			    Business Goal: Constructs a concise text-formatted KPI indicator that displays:
			    - Previous Year's Sales value (PY Value) formatted in millions
			    - Year-over-Year change direction (arrow symbol)
			    - Percentage change in Sales YoY
			    
			    This measure is designed for use in card visuals, KPIs, or table headers to provide
			    a quick, comprehensive view of sales performance compared to the previous year.
			    The output format is: "PY 1.50M ↑ 15.25%"
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance and code readability by calculating values once.
			*/
			VAR Current_Sales = 
			    /*
			        Retrieves the Sales value for the current filter context.
			        This variable calls the base [Sales] measure.
			    */
			    [Sales]
			VAR Previous_Year_Sales =
			    /*
			        Calculates the Sales for the same period in the previous year.
			        CALCULATE: Modifies the filter context for the [Sales] measure.
			        SAMEPERIODLASTYEAR: A time intelligence function that returns a set of dates
			        from the previous year corresponding to the current date context.
			        This is the recommended best practice for accurate YoY comparisons.
			    */
			    CALCULATE ( 
			        [Sales], 
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] ) 
			    )
			VAR Change_Percentage =
			    /*
			        Calculates the Year-over-Year percentage change in Sales.
			        DIVIDE: Safely performs division and handles division by zero errors.
			        - First argument: Numerator (Current - Previous)
			        - Second argument: Denominator (Previous Year value)
			        - Third argument: Alternative result in case of error (BLANK here)
			    */
			    DIVIDE (
			        Current_Sales - Previous_Year_Sales,
			        Previous_Year_Sales,
			        BLANK () // Safe handling of division by zero
			    )
			VAR Is_Sales_Increased = 
			    /*
			        Creates a logical (TRUE/FALSE) variable indicating if sales increased.
			        A positive change percentage means sales grew compared to previous year.
			    */
			    Change_Percentage > 0
			VAR Arrow_Symbol =
			    /*
			        Assigns an arrow symbol based on the direction of the sales change.
			        IF: Returns one of two values based on a logical condition.
			        UNICHAR: Returns the Unicode character for the specified number.
			        - 11165: Upwards arrow (↑) - indicates sales increase (favorable)
			        - 11167: Downwards arrow (↓) - indicates sales decrease (unfavorable)
			        
			        This follows standard business conventions where sales growth is positive
			        and represented by an upward arrow.
			    */
			    IF (
			        Is_Sales_Increased,
			        "▲", // Up arrow for sales increase (good)
			        "▼" // Down arrow for sales decrease/no change (bad)
			    )
			RETURN
			    /*
			        Final conditional check to determine if the KPI should be displayed.
			        IF: Checks if there's a valid percentage change to display.
			        ISBLANK: Returns TRUE if the Change_Percentage is BLANK.
			        This prevents displaying the KPI when there's no data for comparison
			        (e.g., first year of data or missing previous year values).
			    */
			    IF (
			        ISBLANK ( Change_Percentage ),
			        BLANK (),
			        /*
			            Constructs the final KPI string by concatenating multiple elements:
			            - "PY ": Literal text prefix for Previous Year
			            - FORMAT(Previous_Year_Sales, "#,,#,,.00M"): Formats the previous year value
			              in millions with two decimal places using thousand separators
			              (e.g., 1.50M for $1,500,000)
			            - Arrow_Symbol: The directional arrow (↑ or ↓)
			            - FORMAT(Change_Percentage, "0.00%"): Formats the percentage change as
			              a percentage with two decimal places (e.g., 15.25%)
			        */
			        "PY " & FORMAT ( Previous_Year_Sales, "#,,#,,.00M" ) & " " & Arrow_Symbol & " "
			            & FORMAT ( Change_Percentage, "0.00%" )
			    )
			```
		displayFolder: sales
		lineageTag: daca2775-4004-40c0-980d-d1d51f794411

	measure 'Sales Color Optimized' = ```
			
			/*
			    Business Goal: This measure returns a color code (hex) based on the Year-over-Year (YoY)
			    change in Sales. It is designed for conditional formatting in reports to visually
			    indicate performance trends - green for sales growth, red for sales decline,
			    and gray for no change. The measure returns a text value suitable for font color,
			    background color, or icon conditional formatting in various visualizations.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance and code readability by calculating values once.
			*/
			VAR Current_Sales = 
			    /*
			        IFERROR: Evaluates the [Sales] measure and returns it if no error occurs.
			        If an error is encountered, it returns BLANK() instead.
			        This ensures the measure handles calculation errors gracefully without breaking
			        and maintains data cleanliness.
			    */
			    IFERROR( [Sales], BLANK() )
			
			VAR Previous_Year_Sales =
			    /*
			        CALCULATE: Modifies the filter context for the [Sales] measure evaluation.
			        SAMEPERIODLASTYEAR: A time intelligence function that takes a date column
			        and returns a set of dates from the previous year corresponding to the current
			        date context. For example, if viewing March 2024, it returns dates for March 2023.
			        This enables accurate year-over-year comparisons for sales performance.
			    */
			    CALCULATE (
			        IFERROR( [Sales], BLANK() ),
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] )
			    )
			
			// Calculates the absolute Year-over-Year Change: Current Period - Previous Year
			VAR YoY_Change_Absolute = 
			    /*
			        COALESCE: Returns the first expression that does not evaluate to BLANK.
			        Here, it replaces BLANK values with 0 to ensure correct arithmetic operations
			        in the subtraction. This prevents calculation errors when either current or
			        previous year sales data is missing.
			    */
			    COALESCE( Current_Sales, 0 ) - COALESCE( Previous_Year_Sales, 0 )
			
			RETURN
			    /*
			        SWITCH: Evaluates multiple conditions and returns one of several result expressions.
			        TRUE(): Used as the first argument to enable conditional logic based on the value
			        of YoY_Change_Absolute. This structure checks each condition in sequence.
			    */
			    SWITCH (
			        TRUE(),
			        // Condition 1: Sales increased (Green) - Favorable performance
			        YoY_Change_Absolute > 0, "#00A650", 
			        // Condition 2: Sales decreased (Red) - Unfavorable performance
			        YoY_Change_Absolute < 0, "#E60000", 
			        // Condition 3: No change, zero, or BLANK (Gray) - Neutral performance
			        "#7F8C8D" 
			    )
			```
		displayFolder: sales
		lineageTag: 564a6613-a26b-4df3-a93c-121b86726bd6

	measure 'COGS KPI Optimized' = ```
			
			/*
			    Business Goal: Constructs a concise text-formatted KPI indicator.
			    It displays the previous year's COGS value (PY Value), the YoY change direction
			    (arrow symbol), and the percentage change in COGS YoY.
			    This measure is designed for use in card visuals or KPIs to provide a quick,
			    comprehensive view of performance compared to the previous year.
			*/
			VAR Current_COGS = 
			    /*
			        Retrieves the COGS value for the current filter context.
			        This variable calls the base [COGS] measure.
			    */
			    [COGS]
			VAR Previous_Year_COGS =
			    /*
			        Calculates the COGS for the same period in the previous year.
			        CALCULATE: Modifies the filter context for the [COGS] measure.
			        SAMEPERIODLASTYEAR: A time intelligence function that returns a set of dates
			        from the previous year corresponding to the current date context.
			        This is the standard and most accurate method for YoY comparisons.
			    */
			    CALCULATE ( 
			        [COGS], 
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] ) 
			    )
			VAR Change_Percentage =
			    /*
			        Calculates the Year-over-Year percentage change in COGS.
			        DIVIDE: Safely performs division and handles division by zero errors.
			        - First argument: Numerator (Current - Previous)
			        - Second argument: Denominator (Previous Year value)
			        - Third argument: Alternative result in case of error (e.g., division by zero)
			    */
			    DIVIDE (
			        Current_COGS - Previous_Year_COGS,
			        Previous_Year_COGS,
			        BLANK () // Returns BLANK instead of an error if dividing by zero
			    )
			VAR Is_Change_Positive = 
			    /*
			        Creates a logical (TRUE/FALSE) variable indicating if the change was positive.
			        This variable improves code readability for the subsequent IF statement.
			        A positive change means COGS increased (which is typically unfavorable).
			    */
			    Change_Percentage > 0
			VAR Arrow_Symbol =
			    /*
			        Assigns an arrow symbol based on the direction of the change.
			        IF: Returns one of two values based on a logical condition.
			        UNICHAR: Returns the Unicode character for the specified number.
			        - 11165: Upwards arrow (↑) - indicates an increase in COGS (unfavorable)
			        - 11167: Downwards arrow (↓) - indicates a decrease in COGS (favorable)
			    */
			    IF (
			        Is_Change_Positive,
			        "▲", // Up arrow for increase
			        "▼"  // Down arrow for decrease/no change
			    )
			RETURN
			    /*
			        Final conditional check to determine if the KPI should be displayed.
			        IF: Checks if there's a valid percentage change to display.
			        ISBLANK: Returns TRUE if the Change_Percentage is BLANK.
			        This prevents displaying the KPI when there's no data (e.g., first year of data).
			    */
			    IF (
			        ISBLANK ( Change_Percentage ),
			        BLANK (),
			        /*
			            Constructs the final KPI string by concatenating multiple elements:
			            - "PY ": Literal text prefix
			            - FORMAT(Previous_Year_COGS, "#,,#,,.00M"): Formats the previous year value
			              in millions with two decimal places (e.g., 1.50M)
			            - Arrow_Symbol: The directional arrow
			            - FORMAT(Change_Percentage, "0.00%"): Formats the percentage change as
			              a percentage with two decimal places (e.g., 15.25%)
			        */
			        "PY " & FORMAT ( Previous_Year_COGS, "#,,#,,.00M" ) & " " & Arrow_Symbol & " "
			            & FORMAT ( Change_Percentage, "0.00%" )
			    )
			```
		displayFolder: cogs
		lineageTag: ea5432d5-b5ad-4bcc-a9f1-9367e9b6847e

	measure 'COGS Color Optimized' = ```
			
			/*
			    Business Goal: This measure does not return a numeric value but a color code (hex).
			    It is designed to be used in a report visual to conditionally format elements
			    (like KPI icons or font colors) based on the Year-over-Year (YoY) change in COGS.
			    It calculates the current COGS and the COGS from the same period last year,
			    computes the absolute difference, and returns a color based on whether COGS
			    decreased (good, green), increased (bad, red), or remained stable (gray).
			
			    Function Explanation:
			    VAR: Used to declare a variable that stores the result of a DAX expression.
			    Variables improve performance and readability by calculating a value once and reusing it.
			*/
			VAR Current_COGS = 
			    /*
			        IFERROR: Evaluates the first expression and returns it if no error occurs.
			        If an error is encountered, it returns the second expression (BLANK() in this case).
			        This ensures the measure is robust against calculation errors.
			    */
			    IFERROR( [COGS], BLANK() )
			
			VAR Previous_Year_COGS =
			    /*
			        CALCULATE: The primary function for context modification in DAX.
			        It evaluates an expression (IFERROR([COGS], BLANK())) in a modified filter context.
			        SAMEPERIODLASTYEAR: A time intelligence function that takes a date column and
			        returns a set of dates from the previous year corresponding to the current date context.
			        For example, if the current context is March 2024, it returns dates for March 2023.
			    */
			    CALCULATE (
			        IFERROR( [COGS], BLANK() ),
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] )
			    )
			
			// Calculates the absolute Year-over-Year Change: Current Period - Previous Year
			VAR YoY_Change_Absolute = 
			    /*
			        COALESCE: Returns the first expression that does not evaluate to BLANK.
			        If the first expression is blank, it checks the second, and so on.
			        Here, it replaces BLANK values with 0 to ensure correct arithmetic operations.
			    */
			    COALESCE( Current_COGS, 0 ) - COALESCE( Previous_Year_COGS, 0 )
			
			RETURN
			    /*
			        SWITCH: Evaluates a list of conditions and returns one of multiple result expressions.
			        TRUE(): Used as the first argument to SWITCH to enable conditional logic based on the value of YoY_Change_Absolute.
			        This structure checks each condition in sequence and returns the corresponding color hex code.
			        - Green (#00A650) for a decrease in COGS (which is typically favorable).
			        - Red (#E60000) for an increase in COGS (which is typically unfavorable).
			        - Gray (#7F8C8D) for no change or if the value is BLANK (coerced to 0).
			    */
			    SWITCH (
			        TRUE(),
			        // Condition 1: COGS decreased (Green) - Favorable
			        YoY_Change_Absolute < 0, "#00A650", 
			        // Condition 2: COGS increased (Red) - Unfavorable
			        YoY_Change_Absolute > 0, "#E60000", 
			        // Condition 3: No change, 0, or BLANK (Gray) - Neutral
			        "#7F8C8D" 
			    )
			```
		displayFolder: cogs
		lineageTag: aa06622d-53ee-4262-bb31-5d45c574d0e4

	measure Profit =
			
			/*
			    Business Goal: Establishes a base aggregate measure for the total Profit
			    by summing the values from the 'financials[Profit]' column.
			    This is a fundamental metric that serves as the foundation for further
			    analytical calculations, KPIs, and comparative analysis throughout the report.
			
			    Function Explanation:
			    SUM: A basic aggregation function that returns the sum of all the numbers
			    in the specified column. It operates within the current filter context,
			    meaning it will automatically adjust based on any filters, slicers, or
			    visual context applied in the report.
			
			    This measure is typically used as:
			    - A standalone KPI for overall profitability
			    - A base for time intelligence calculations (YoY, MTD, QTD)
			    - A numerator or denominator in ratio calculations
			    - A core metric for conditional formatting and visualizations
			*/
			SUM ( financials[Profit] )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: profit
		lineageTag: 3841f539-63f6-4c8c-a37e-c51d59a3262b

	measure 'Profit KPI Optimized' = ```
			
			/*
			    Business Goal: Constructs a concise text-formatted KPI indicator that displays:
			    - Previous Year's Profit value (PY Value)
			    - Year-over-Year change direction (arrow symbol)
			    - Percentage change in Profit YoY
			    
			    This measure is designed for use in card visuals, KPIs, or table headers to provide
			    a quick, comprehensive view of profit performance compared to the previous year.
			    The output format is: "PY 1.50M ↑ 15.25%"
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance and code readability by calculating values once.
			*/
			VAR Current_Profit = 
			    /*
			        Retrieves the Profit value for the current filter context.
			        This variable calls the base [Profit] measure.
			    */
			    [Profit]
			VAR Previous_Year_Profit =
			    /*
			        Calculates the Profit for the same period in the previous year.
			        CALCULATE: Modifies the filter context for the [Profit] measure.
			        SAMEPERIODLASTYEAR: A time intelligence function that returns a set of dates
			        from the previous year corresponding to the current date context.
			        This is the standard method for accurate YoY comparisons.
			    */
			    CALCULATE ( 
			        [Profit], 
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] ) 
			    )
			VAR Change_Percentage =
			    /*
			        Calculates the Year-over-Year percentage change in Profit.
			        DIVIDE: Safely performs division and handles division by zero errors.
			        - First argument: Numerator (Current - Previous)
			        - Second argument: Denominator (Previous Year value)
			        - Third argument: Alternative result in case of error (BLANK here)
			    */
			    DIVIDE (
			        Current_Profit - Previous_Year_Profit,
			        Previous_Year_Profit,
			        BLANK () // Safe handling of division by zero
			    )
			VAR Is_Profit_Increased = 
			    /*
			        Creates a logical (TRUE/FALSE) variable indicating if profit increased.
			        A positive change percentage means profit grew compared to previous year.
			    */
			    Change_Percentage > 0
			VAR Arrow_Symbol =
			    /*
			        Assigns an arrow symbol based on the direction of the profit change.
			        IF: Returns one of two values based on a logical condition.
			        UNICHAR: Returns the Unicode character for the specified number.
			        - 11165: Upwards arrow (↑) - indicates profit increase (favorable)
			        - 11167: Downwards arrow (↓) - indicates profit decrease (unfavorable)
			        
			        Note: This correctly associates upward arrow with profit growth,
			        which is the standard business convention for positive performance.
			    */
			    IF (
			        Is_Profit_Increased,
			        "▲", // Up arrow for profit increase (good)
			        "▼"  // Down arrow for profit decrease/no change (bad)
			    )
			RETURN
			    /*
			        Final conditional check to determine if the KPI should be displayed.
			        IF: Checks if there's a valid percentage change to display.
			        ISBLANK: Returns TRUE if the Change_Percentage is BLANK.
			        This prevents displaying the KPI when there's no data for comparison
			        (e.g., first year of data or missing previous year values).
			    */
			    IF (
			        ISBLANK ( Change_Percentage ),
			        BLANK (),
			        /*
			            Constructs the final KPI string by concatenating multiple elements:
			            - "PY ": Literal text prefix for Previous Year
			            - FORMAT(Previous_Year_Profit, "#,,#,,.00M"): Formats the previous year value
			              in millions with two decimal places (e.g., 1.50M for $1,500,000)
			            - Arrow_Symbol: The directional arrow (↑ or ↓)
			            - FORMAT(Change_Percentage, "0.00%"): Formats the percentage change as
			              a percentage with two decimal places (e.g., 15.25%)
			        */
			        "PY " & FORMAT ( Previous_Year_Profit, "#,,#,,.00M" ) & " " & Arrow_Symbol & " "
			            & FORMAT ( Change_Percentage, "0.00%" )
			    )
			```
		displayFolder: profit
		lineageTag: dd035eb9-7259-4dc0-a085-2b57b4bcf7cd

	measure 'Profit Color Optimized' = ```
			
			/*
			    Business Goal: This measure returns a color code (hex) based on the Year-over-Year (YoY)
			    change in Profit. It is designed for conditional formatting in reports to visually
			    indicate performance trends - green for profit growth, red for profit decline,
			    and gray for no change. Unlike numeric measures, this returns a text value
			    suitable for font color, background color, or icon conditional formatting.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance and code readability.
			*/
			VAR Current_Profit = 
			    /*
			        IFERROR: Evaluates the [Profit] measure and returns it if no error occurs.
			        If an error is encountered, it returns BLANK() instead.
			        This ensures the measure handles calculation errors gracefully without breaking.
			    */
			    IFERROR( [Profit], BLANK() )
			
			VAR Previous_Year_Profit =
			    /*
			        CALCULATE: Modifies the filter context for the [Profit] measure evaluation.
			        SAMEPERIODLASTYEAR: A time intelligence function that takes a date column
			        and returns a set of dates from the previous year corresponding to the current
			        date context. For example, if viewing Q1 2024, it returns dates for Q1 2023.
			        This enables accurate year-over-year comparisons.
			    */
			    CALCULATE (
			        IFERROR( [Profit], BLANK() ),
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] )
			    )
			
			// Calculates the absolute Year-over-Year Change: Current Period - Previous Year
			VAR YoY_Change_Absolute = 
			    /*
			        COALESCE: Returns the first expression that does not evaluate to BLANK.
			        Here, it replaces BLANK values with 0 to ensure correct arithmetic operations
			        in the subtraction. This prevents errors when either current or previous year
			        data is missing.
			    */
			    COALESCE( Current_Profit, 0 ) - COALESCE( Previous_Year_Profit, 0 )
			
			RETURN
			    /*
			        SWITCH: Evaluates multiple conditions and returns one of several result expressions.
			        TRUE(): Used as the first argument to enable conditional logic based on the value
			        of YoY_Change_Absolute. This structure checks each condition in sequence.
			    */
			    SWITCH (
			        TRUE(),
			        // Condition 1: Profit increased (Green) - Favorable
			        YoY_Change_Absolute > 0, "#00A650", 
			        // Condition 2: Profit decreased (Red) - Unfavorable
			        YoY_Change_Absolute < 0, "#E60000", 
			        // Condition 3: No change, zero, or BLANK (Gray) - Neutral
			        "#7F8C8D" 
			    )
			```
		displayFolder: profit
		lineageTag: bdd3eb93-aeca-4623-bc15-3c19d80b7a5f

	measure 'Units Sold' =
			
			/*
			    Business Goal: Establishes a base aggregate measure for the total Units Sold
			    by summing the values from the 'financials[Units Sold]' column.
			    This is a fundamental metric that serves as the foundation for further
			    analytical calculations, KPIs, volume analysis, and business intelligence
			    throughout the entire reporting solution.
			
			    Function Explanation:
			    SUM: A basic aggregation function that returns the sum of all the numbers
			    in the specified column. It operates within the current filter context,
			    meaning it will automatically adjust based on any filters, slicers, or
			    visual context applied in the report.
			
			    This measure is typically used as:
			    - A standalone KPI for overall sales volume performance
			    - A base for time intelligence calculations (YoY, MTD, QTD, YTD volume trends)
			    - A numerator or denominator in ratio calculations (units per transaction, average unit price)
			    - A core metric for volume-based conditional formatting and various visualizations
			    - A foundation for inventory planning and demand forecasting analysis
			*/
			SUM ( financials[Units Sold] )
		displayFolder: units sold
		lineageTag: 16222a82-f60b-4a61-8863-ed3b34393c80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Units Sold KPI Optimized' = ```
			
			/*
			    Business Goal: Constructs a concise text-formatted KPI indicator that displays:
			    - Previous Year's Units Sold value (PY Value) formatted in millions
			    - Year-over-Year change direction (arrow symbol)
			    - Percentage change in Units Sold YoY
			    
			    This measure is designed for use in card visuals, KPIs, or table headers to provide
			    a quick, comprehensive view of sales volume performance compared to the previous year.
			    The output format is: "PY 1.50M ↑ 15.25%"
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance and code readability by calculating values once.
			*/
			VAR Current_Units_Sold = 
			    /*
			        Retrieves the Units Sold value for the current filter context.
			        This variable calls the base [Units Sold] measure.
			    */
			    [Units Sold]
			VAR Previous_Year_Units_Sold =
			    /*
			        Calculates the Units Sold for the same period in the previous year.
			        CALCULATE: Modifies the filter context for the [Units Sold] measure.
			        SAMEPERIODLASTYEAR: A time intelligence function that returns a set of dates
			        from the previous year corresponding to the current date context.
			        This is the recommended best practice for accurate YoY volume comparisons.
			    */
			    CALCULATE ( 
			        [Units Sold], 
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] ) 
			    )
			VAR Change_Percentage =
			    /*
			        Calculates the Year-over-Year percentage change in Units Sold.
			        DIVIDE: Safely performs division and handles division by zero errors.
			        - First argument: Numerator (Current - Previous)
			        - Second argument: Denominator (Previous Year value)
			        - Third argument: Alternative result in case of error (BLANK here)
			    */
			    DIVIDE (
			        Current_Units_Sold - Previous_Year_Units_Sold,
			        Previous_Year_Units_Sold,
			        BLANK () // Safe handling of division by zero
			    )
			VAR Is_Units_Increased = 
			    /*
			        Creates a logical (TRUE/FALSE) variable indicating if units sold increased.
			        A positive change percentage means sales volume grew compared to previous year.
			    */
			    Change_Percentage > 0
			VAR Arrow_Symbol =
			    /*
			        Assigns an arrow symbol based on the direction of the volume change.
			        IF: Returns one of two values based on a logical condition.
			        UNICHAR: Returns the Unicode character for the specified number.
			        - 11165: Upwards arrow (↑) - indicates volume increase (favorable)
			        - 11167: Downwards arrow (↓) - indicates volume decrease (unfavorable)
			        
			        This follows standard business conventions where sales volume growth is positive
			        and represented by an upward arrow.
			    */
			    IF (
			        Is_Units_Increased,
			        "▲", // Up arrow for volume increase (good)
			        "▼"  // Down arrow for volume decrease/no change (bad)
			    )
			RETURN
			    /*
			        Final conditional check to determine if the KPI should be displayed.
			        IF: Checks if there's a valid percentage change to display.
			        ISBLANK: Returns TRUE if the Change_Percentage is BLANK.
			        This prevents displaying the KPI when there's no data for comparison
			        (e.g., first year of data or missing previous year values).
			    */
			    IF (
			        ISBLANK ( Change_Percentage ),
			        BLANK (),
			        /*
			            Constructs the final KPI string by concatenating multiple elements:
			            - "PY ": Literal text prefix for Previous Year
			            - FORMAT(Previous_Year_Units_Sold, "#,,#,,.00M"): Formats the previous year value
			              in millions with two decimal places using thousand separators
			              (e.g., 1.50M for 1,500,000 units)
			            - Arrow_Symbol: The directional arrow (↑ or ↓)
			            - FORMAT(Change_Percentage, "0.00%"): Formats the percentage change as
			              a percentage with two decimal places (e.g., 15.25%)
			        */
			        "PY " & FORMAT ( Previous_Year_Units_Sold, "#,,#,,.00M" ) & " " & Arrow_Symbol & " "
			            & FORMAT ( Change_Percentage, "0.00%" )
			    )
			```
		displayFolder: units sold
		lineageTag: f661ed43-ab41-41a1-91fa-8e232a5c9c01

	measure 'Units Sold Color Optimized' = ```
			
			/*
			    Business Goal: This measure returns a color code (hex) based on the Year-over-Year (YoY)
			    change in Units Sold. It is designed for conditional formatting in reports to visually
			    indicate volume performance trends - green for volume growth, red for volume decline,
			    and gray for no change. The measure returns a text value suitable for font color,
			    background color, or icon conditional formatting in various visualizations.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance and code readability by calculating values once.
			*/
			VAR Current_Units_Sold = 
			    /*
			        IFERROR: Evaluates the [Units Sold] measure and returns it if no error occurs.
			        If an error is encountered, it returns BLANK() instead.
			        This ensures the measure handles calculation errors gracefully without breaking
			        and maintains data cleanliness.
			    */
			    IFERROR( [Units Sold], BLANK() )
			
			VAR Previous_Year_Units_Sold =
			    /*
			        CALCULATE: Modifies the filter context for the [Units Sold] measure evaluation.
			        SAMEPERIODLASTYEAR: A time intelligence function that takes a date column
			        and returns a set of dates from the previous year corresponding to the current
			        date context. For example, if viewing March 2024, it returns dates for March 2023.
			        This enables accurate year-over-year comparisons for volume performance.
			    */
			    CALCULATE (
			        IFERROR( [Units Sold], BLANK() ),
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] )
			    )
			
			// Calculates the absolute Year-over-Year Change: Current Period - Previous Year
			VAR YoY_Change_Absolute = 
			    /*
			        COALESCE: Returns the first expression that does not evaluate to BLANK.
			        Here, it replaces BLANK values with 0 to ensure correct arithmetic operations
			        in the subtraction. This prevents calculation errors when either current or
			        previous year units sold data is missing.
			    */
			    COALESCE( Current_Units_Sold, 0 ) - COALESCE( Previous_Year_Units_Sold, 0 )
			
			RETURN
			    /*
			        SWITCH: Evaluates multiple conditions and returns one of several result expressions.
			        TRUE(): Used as the first argument to enable conditional logic based on the value
			        of YoY_Change_Absolute. This structure checks each condition in sequence.
			    */
			    SWITCH (
			        TRUE(),
			        // Condition 1: Units Sold increased (Green) - Favorable volume performance
			        YoY_Change_Absolute > 0, "#00A650", 
			        // Condition 2: Units Sold decreased (Red) - Unfavorable volume performance
			        YoY_Change_Absolute < 0, "#E60000", 
			        // Condition 3: No change, zero, or BLANK (Gray) - Neutral volume performance
			        "#7F8C8D" 
			    )
			```
		displayFolder: units sold
		lineageTag: 5a1b6d46-8648-4c3f-ac57-cf74ef3246a2

	measure 'Max Sales Optimized' = ```
			
			/*
			    Business Goal: In a tabular visualization context (e.g., a month-by-month table),
			    this measure returns the Sales value ONLY for the specific row (period) where Sales
			    reached its maximum value within the entire currently selected time period (e.g., year).
			    All other rows will display BLANK(). This creates a visual highlight that instantly
			    identifies the peak sales period in the selected timeframe.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance by calculating values once and reusing them.
			*/
			VAR Current_Sales = 
			    /*
			        Retrieves the Sales value for the current filter context (e.g., for the current month/row).
			        This is evaluated in the context of each row in the visual and represents the sales
			        for that specific period.
			    */
			    [Sales]
			VAR Max_Sales_Value =
			    /*
			        MAXX: An iterator function that scans through a table and returns the maximum value
			        of an expression evaluated for each row.
			        
			        ALLSELECTED: Returns all rows in a table while respecting the current user selections
			        from slicers, report filters, and other visual interactions. This ensures we calculate
			        the maximum sales only within the timeframe the user is currently viewing.
			        
			        Combined, this calculates the maximum Sales value across all dates that are
			        currently selected in the report. The variable is computed once and reused for
			        all row comparisons, providing significant performance optimization.
			    */
			    MAXX ( ALLSELECTED ( 'Dates Optimized' ), [Sales] )
			
			RETURN
			    /*
			        Two-layer conditional logic to control the final output:
			        - First, check if there's any Sales value in the current row
			        - Then, check if the current row's Sales equals the maximum Sales in the selected period
			    */
			    IF (
			        ISBLANK ( Current_Sales ),
			        /*
			            ISBLANK: Returns TRUE if the Current_Sales is BLANK.
			            If there's no Sales data for the current period, return BLANK to maintain
			            data cleanliness and avoid displaying misleading zeros.
			        */
			        BLANK (),
			        /*
			            Second IF: Compares the current row's Sales with the maximum Sales value.
			            If they are equal, this row contains the period with maximum sales performance.
			        */
			        IF (
			            Current_Sales = Max_Sales_Value,
			            /*
			                Returns the Current_Sales value only for the row that contains
			                the maximum value. This creates a visual highlight where only the
			                peak sales period displays its sales value, making it stand out.
			            */
			            Current_Sales,
			            /*
			                Returns BLANK() for all rows that don't contain the maximum Sales value.
			                This creates a clean visual effect where only the peak sales period
			                is prominently displayed, facilitating quick business insights.
			            */
			            BLANK ()
			        )
			    )
			```
		displayFolder: sales
		lineageTag: e10cf3df-16c2-48f9-a402-47c2d2f12db4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min Sales Optimized' = ```
			
			/*
			    Business Goal: In a tabular visualization context (e.g., a month-by-month table),
			    this measure returns the Sales value ONLY for the specific row (period) where Sales
			    reached its minimum value within the entire currently selected time period (e.g., year).
			    All other rows will display BLANK(). This creates a visual highlight that instantly
			    identifies the lowest sales period in the selected timeframe, complementing the
			    "Max Sales Optimized" measure for comprehensive sales performance analysis.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance by calculating values once and reusing them.
			*/
			VAR Current_Sales = 
			    /*
			        Retrieves the Sales value for the current filter context (e.g., for the current month/row).
			        This is evaluated in the context of each row in the visual and represents the sales
			        for that specific period.
			    */
			    [Sales]
			VAR Min_Sales_Value =
			    /*
			        MINX: An iterator function that scans through a table and returns the minimum value
			        of an expression evaluated for each row.
			        
			        ALLSELECTED: Returns all rows in a table while respecting the current user selections
			        from slicers, report filters, and other visual interactions. This ensures we calculate
			        the minimum sales only within the timeframe the user is currently viewing.
			        
			        Combined, this calculates the minimum Sales value across all dates that are
			        currently selected in the report. The variable is computed once and reused for
			        all row comparisons, providing significant performance optimization.
			    */
			    MINX ( ALLSELECTED ( 'Dates Optimized' ), [Sales] )
			
			RETURN
			    /*
			        Two-layer conditional logic to control the final output:
			        - First, check if there's any Sales value in the current row
			        - Then, check if the current row's Sales equals the minimum Sales in the selected period
			    */
			    IF (
			        ISBLANK ( Current_Sales ),
			        /*
			            ISBLANK: Returns TRUE if the Current_Sales is BLANK.
			            If there's no Sales data for the current period, return BLANK to maintain
			            data cleanliness and avoid displaying misleading information.
			        */
			        BLANK (),
			        /*
			            Second IF: Compares the current row's Sales with the minimum Sales value.
			            If they are equal, this row contains the period with minimum sales performance.
			        */
			        IF (
			            Current_Sales = Min_Sales_Value,
			            /*
			                Returns the Current_Sales value only for the row that contains
			                the minimum value. This creates a visual highlight where only the
			                lowest sales period displays its sales value, making it stand out
			                for further investigation or analysis.
			            */
			            Current_Sales,
			            /*
			                Returns BLANK() for all rows that don't contain the minimum Sales value.
			                This creates a clean visual effect where only the lowest sales period
			                is prominently displayed, helping identify potential problem areas
			                or seasonal troughs.
			            */
			            BLANK ()
			        )
			    )
			```
		displayFolder: sales
		lineageTag: 7dea7483-55be-4171-8e61-f1d6facc59df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max COGS Optimized' = ```
			
			/*
			    Business Goal: In a tabular visualization context (e.g., a month-by-month table),
			    this measure returns the COGS value ONLY for the specific row (period) where COGS
			    reached its maximum value within the entire currently selected time period (e.g., year).
			    All other rows will display BLANK(). This helps quickly identify the peak COGS period
			    in a time series visualization.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance and code readability.
			*/
			VAR Current_COGS = 
			    /*
			        Retrieves the COGS value for the current filter context (e.g., for the current month/row).
			        This is evaluated in the context of each row in the visual.
			    */
			    [COGS]
			VAR Max_COGS_Value =
			    /*
			        MAXX: An iterator function that iterates over a table and returns the maximum value
			        of an expression evaluated for each row.
			        
			        ALLSELECTED: Returns all rows in a table, ignoring context filters but keeping
			        filters from slicers, report filters, etc. This creates the "currently selected"
			        context that the user sees in the report.
			        
			        Combined, this calculates the maximum COGS value across all dates that are
			        currently selected/visible in the report, regardless of the current row context.
			        This variable is computed once and reused, improving performance.
			    */
			    MAXX ( ALLSELECTED ( 'Dates Optimized' ), [COGS] )
			
			RETURN
			    /*
			        Two-layer IF statement to control the final output:
			        - First, check if there's any COGS value in the current row
			        - Then, check if the current row's COGS equals the maximum COGS in the selected period
			    */
			    IF (
			        ISBLANK ( Current_COGS ),
			        /*
			            ISBLANK: Returns TRUE if the Current_COGS is BLANK.
			            If there's no COGS data for the current period, return BLANK.
			        */
			        BLANK (),
			        /*
			            Second IF: Compares the current row's COGS with the maximum value.
			            If they are equal, this row contains the maximum COGS value.
			        */
			        IF (
			            Current_COGS = Max_COGS_Value,
			            /*
			                Returns the Current_COGS value only for the row that contains
			                the maximum value. This will make only one row (or multiple rows
			                in case of ties) display the COGS value in the visual.
			            */
			            Current_COGS,
			            /*
			                Returns BLANK() for all rows that don't contain the maximum COGS value.
			                This creates a visual effect where only the peak period is highlighted.
			            */
			            BLANK ()
			        )
			    )
			```
		displayFolder: cogs
		lineageTag: 1c507070-fd0e-4619-af9c-219563bc9144

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min COGS Optimized' = ```
			
			/*
			    Business Goal: In a tabular visualization context (e.g., a month-by-month table),
			    this measure returns the COGS value ONLY for the specific row (period) where COGS
			    reached its minimum value within the entire currently selected time period (e.g., year).
			    All other rows will display BLANK(). This helps quickly identify the lowest COGS period
			    in a time series visualization, complementing the "Max COGS Optimized" measure.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance by calculating values once and reusing them.
			*/
			VAR Current_COGS = 
			    /*
			        Retrieves the COGS value for the current filter context (e.g., for the current month/row).
			        This is evaluated in the context of each row in the visual.
			    */
			    [COGS]
			VAR Min_COGS_Value =
			    /*
			        MINX: An iterator function that iterates over a table and returns the minimum value
			        of an expression evaluated for each row.
			        
			        ALLSELECTED: Returns all rows in a table, ignoring context filters but keeping
			        filters from slicers, report filters, and other user selections. This creates
			        the "currently selected" context that the user sees in the report.
			        
			        Combined, this calculates the minimum COGS value across all dates that are
			        currently selected/visible in the report. The variable is computed once and
			        reused for all row comparisons, providing significant performance optimization.
			    */
			    MINX ( ALLSELECTED ( 'Dates Optimized' ), [COGS] )
			
			RETURN
			    /*
			        Two-layer IF statement to control the final output:
			        - First, check if there's any COGS value in the current row
			        - Then, check if the current row's COGS equals the minimum COGS in the selected period
			    */
			    IF (
			        ISBLANK ( Current_COGS ),
			        /*
			            ISBLANK: Returns TRUE if the Current_COGS is BLANK.
			            If there's no COGS data for the current period, return BLANK to avoid
			            displaying zeros or errors for missing data points.
			        */
			        BLANK (),
			        /*
			            Second IF: Compares the current row's COGS with the minimum value.
			            If they are equal, this row contains the minimum COGS value.
			        */
			        IF (
			            Current_COGS = Min_COGS_Value,
			            /*
			                Returns the Current_COGS value only for the row that contains
			                the minimum value. This will make only one row (or multiple rows
			                in case of ties) display the COGS value in the visual.
			            */
			            Current_COGS,
			            /*
			                Returns BLANK() for all rows that don't contain the minimum COGS value.
			                This creates a visual effect where only the lowest period is highlighted,
			                making it easy to identify cost efficiency peaks.
			            */
			            BLANK ()
			        )
			    )
			```
		displayFolder: cogs
		lineageTag: 4d69aac6-a71b-485b-a305-e37c5ab23624

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Profit Optimized' = ```
			
			/*
			    Business Goal: In a tabular visualization context (e.g., a month-by-month table),
			    this measure returns the Profit value ONLY for the specific row (period) where Profit
			    reached its maximum value within the entire currently selected time period (e.g., year).
			    All other rows will display BLANK(). This creates a visual highlight that instantly
			    identifies the most profitable period in the selected timeframe.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance by calculating values once and reusing them.
			*/
			VAR Current_Profit = 
			    /*
			        Retrieves the Profit value for the current filter context (e.g., for the current month/row).
			        This is evaluated in the context of each row in the visual and represents the profit
			        for that specific period.
			    */
			    [Profit]
			VAR Max_Profit_Value =
			    /*
			        MAXX: An iterator function that scans through a table and returns the maximum value
			        of an expression evaluated for each row.
			        
			        ALLSELECTED: Returns all rows in a table while respecting the current user selections
			        from slicers, report filters, and other visual interactions. This ensures we calculate
			        the maximum profit only within the timeframe the user is currently viewing.
			        
			        Combined, this calculates the maximum Profit value across all dates that are
			        currently selected in the report. The variable is computed once and reused for
			        all row comparisons, providing significant performance optimization, especially
			        in large datasets.
			    */
			    MAXX ( ALLSELECTED ( 'Dates Optimized' ), [Profit] )
			
			RETURN
			    /*
			        Two-layer conditional logic to control the final output:
			        - First, check if there's any Profit value in the current row
			        - Then, check if the current row's Profit equals the maximum Profit in the selected period
			    */
			    IF (
			        ISBLANK ( Current_Profit ),
			        /*
			            ISBLANK: Returns TRUE if the Current_Profit is BLANK.
			            If there's no Profit data for the current period, return BLANK to maintain
			            data cleanliness and avoid displaying misleading zeros.
			        */
			        BLANK (),
			        /*
			            Second IF: Compares the current row's Profit with the maximum Profit value.
			            If they are equal, this row contains the period with maximum profitability.
			        */
			        IF (
			            Current_Profit = Max_Profit_Value,
			            /*
			                Returns the Current_Profit value only for the row that contains
			                the maximum value. This creates a visual highlight where only the
			                most profitable period displays its profit value, making it stand out.
			            */
			            Current_Profit,
			            /*
			                Returns BLANK() for all rows that don't contain the maximum Profit value.
			                This creates a clean visual effect where only the peak profitability period
			                is prominently displayed, facilitating quick business insights.
			            */
			            BLANK ()
			        )
			    )
			```
		displayFolder: profit
		lineageTag: b44d5dd9-86be-4227-b491-e951267f1691

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min Profit Optimized' = ```
			
			/*
			    Business Goal: In a tabular visualization context (e.g., a month-by-month table),
			    this measure returns the Profit value ONLY for the specific row (period) where Profit
			    reached its minimum value within the entire currently selected time period (e.g., year).
			    All other rows will display BLANK(). This creates a visual highlight that instantly
			    identifies the least profitable period in the selected timeframe, complementing the
			    "Max Profit Optimized" measure for comprehensive performance analysis.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance by calculating values once and reusing them.
			*/
			VAR Current_Profit = 
			    /*
			        Retrieves the Profit value for the current filter context (e.g., for the current month/row).
			        This is evaluated in the context of each row in the visual and represents the profit
			        for that specific period.
			    */
			    [Profit]
			VAR Min_Profit_Value =
			    /*
			        MINX: An iterator function that scans through a table and returns the minimum value
			        of an expression evaluated for each row.
			        
			        ALLSELECTED: Returns all rows in a table while respecting the current user selections
			        from slicers, report filters, and other visual interactions. This ensures we calculate
			        the minimum profit only within the timeframe the user is currently viewing.
			        
			        Combined, this calculates the minimum Profit value across all dates that are
			        currently selected in the report. The variable is computed once and reused for
			        all row comparisons, providing significant performance optimization.
			    */
			    MINX ( ALLSELECTED ( 'Dates Optimized' ), [Profit] )
			
			RETURN
			    /*
			        Two-layer conditional logic to control the final output:
			        - First, check if there's any Profit value in the current row
			        - Then, check if the current row's Profit equals the minimum Profit in the selected period
			    */
			    IF (
			        ISBLANK ( Current_Profit ),
			        /*
			            ISBLANK: Returns TRUE if the Current_Profit is BLANK.
			            If there's no Profit data for the current period, return BLANK to maintain
			            data cleanliness and avoid displaying misleading information.
			        */
			        BLANK (),
			        /*
			            Second IF: Compares the current row's Profit with the minimum Profit value.
			            If they are equal, this row contains the period with minimum profitability.
			        */
			        IF (
			            Current_Profit = Min_Profit_Value,
			            /*
			                Returns the Current_Profit value only for the row that contains
			                the minimum value. This creates a visual highlight where only the
			                least profitable period displays its profit value, making it stand out
			                for further investigation or analysis.
			            */
			            Current_Profit,
			            /*
			                Returns BLANK() for all rows that don't contain the minimum Profit value.
			                This creates a clean visual effect where only the lowest profitability period
			                is prominently displayed, helping identify potential problem areas.
			            */
			            BLANK ()
			        )
			    )
			```
		displayFolder: profit
		lineageTag: 40060aaa-2f50-422b-930d-e2efa11d5ec5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Units Sold Optimized' = ```
			
			/*
			    Business Goal: In a tabular visualization context, this measure returns the 
			    Units Sold value ONLY for the specific row (period) where the number of units 
			    reached its maximum value within the entire currently selected time period.
			    All other rows will display BLANK(). This creates a visual highlight that 
			    instantly identifies the peak volume period in the selected timeframe.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance by calculating values once and reusing them.
			*/
			VAR Current_Units_Sold = 
			    /*
			        Retrieves the Units Sold value for the current filter context (e.g., for the current month/row).
			        This is evaluated in the context of each row in the visual and represents the units sold
			        for that specific period.
			    */
			    [Units Sold]
			VAR Max_Units_Sold_Value =
			    /*
			        MAXX: An iterator function that scans through a table and returns the maximum value
			        of an expression evaluated for each row.
			        
			        ALLSELECTED: Returns all rows in a table while respecting the current user selections
			        from slicers, report filters, and other visual interactions. This ensures we calculate
			        the maximum units sold only within the timeframe the user is currently viewing.
			        
			        Combined, this calculates the maximum Units Sold value across all dates that are
			        currently selected in the report. The variable is computed once and reused for
			        all row comparisons, providing significant performance optimization.
			    */
			    MAXX ( ALLSELECTED ( 'Dates Optimized' ), [Units Sold] )
			
			RETURN
			    /*
			        Two-layer conditional logic to control the final output:
			        - First, check if there's any Units Sold value in the current row
			        - Then, check if the current row's Units Sold equals the maximum Units Sold in the selected period
			    */
			    IF (
			        ISBLANK ( Current_Units_Sold ),
			        /*
			            ISBLANK: Returns TRUE if the Current_Units_Sold is BLANK.
			            If there's no Units Sold data for the current period, return BLANK to maintain
			            data cleanliness and avoid displaying misleading zeros.
			        */
			        BLANK (),
			        /*
			            Second IF: Compares the current row's Units Sold with the maximum Units Sold value.
			            If they are equal, this row contains the period with maximum sales volume.
			        */
			        IF (
			            Current_Units_Sold = Max_Units_Sold_Value,
			            /*
			                Returns the Current_Units_Sold value only for the row that contains
			                the maximum value. This creates a visual highlight where only the
			                peak volume period displays its units sold value, making it stand out.
			            */
			            Current_Units_Sold,
			            /*
			                Returns BLANK() for all rows that don't contain the maximum Units Sold value.
			                This creates a clean visual effect where only the peak volume period
			                is prominently displayed, facilitating quick volume analysis.
			            */
			            BLANK ()
			        )
			    )
			```
		displayFolder: units sold
		lineageTag: 7c172096-1681-4767-bb4e-26f0b0454a19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min Units Sold Optimized' = ```
			
			/*
			    Business Goal: In a tabular visualization context, this measure returns the 
			    Units Sold value ONLY for the specific row (period) where the number of units 
			    reached its minimum value within the entire currently selected time period.
			    All other rows will display BLANK(). This creates a visual highlight that 
			    instantly identifies the lowest volume period in the selected timeframe,
			    complementing the "Max Units Sold Optimized" measure for comprehensive volume analysis.
			
			    Function Explanation:
			    VAR: Used to declare variables that store intermediate calculation results.
			    This improves performance by calculating values once and reusing them.
			*/
			VAR Current_Units_Sold = 
			    /*
			        Retrieves the Units Sold value for the current filter context (e.g., for the current month/row).
			        This is evaluated in the context of each row in the visual and represents the units sold
			        for that specific period.
			    */
			    [Units Sold]
			VAR Min_Units_Sold_Value =
			    /*
			        MINX: An iterator function that scans through a table and returns the minimum value
			        of an expression evaluated for each row.
			        
			        ALLSELECTED: Returns all rows in a table while respecting the current user selections
			        from slicers, report filters, and other visual interactions. This ensures we calculate
			        the minimum units sold only within the timeframe the user is currently viewing.
			        
			        Combined, this calculates the minimum Units Sold value across all dates that are
			        currently selected in the report. The variable is computed once and reused for
			        all row comparisons, providing significant performance optimization.
			    */
			    MINX ( ALLSELECTED ( 'Dates Optimized' ), [Units Sold] )
			
			RETURN
			    /*
			        Two-layer conditional logic to control the final output:
			        - First, check if there's any Units Sold value in the current row
			        - Then, check if the current row's Units Sold equals the minimum Units Sold in the selected period
			    */
			    IF (
			        ISBLANK ( Current_Units_Sold ),
			        /*
			            ISBLANK: Returns TRUE if the Current_Units_Sold is BLANK.
			            If there's no Units Sold data for the current period, return BLANK to maintain
			            data cleanliness and avoid displaying misleading information.
			        */
			        BLANK (),
			        /*
			            Second IF: Compares the current row's Units Sold with the minimum Units Sold value.
			            If they are equal, this row contains the period with minimum sales volume.
			        */
			        IF (
			            Current_Units_Sold = Min_Units_Sold_Value,
			            /*
			                Returns the Current_Units_Sold value only for the row that contains
			                the minimum value. This creates a visual highlight where only the
			                lowest volume period displays its units sold value, making it stand out
			                for further investigation or analysis.
			            */
			            Current_Units_Sold,
			            /*
			                Returns BLANK() for all rows that don't contain the minimum Units Sold value.
			                This creates a clean visual effect where only the lowest volume period
			                is prominently displayed, helping identify potential problem areas
			                or seasonal troughs in demand.
			            */
			            BLANK ()
			        )
			    )
			```
		displayFolder: units sold
		lineageTag: 5335aca4-684a-4c10-a588-1718c8417b7a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Transparent Color' = ```
			
			/*
			    Business Goal: Returns a constant HEX color code value (#RRGGBBAA) 
			    representing a fully transparent color. This measure is used for 
			    conditional formatting to hide visual elements or make their background transparent.
			    
			    The color code follows the 8-digit HEX format:
			    - First 6 digits: RRGGBB (Red, Green, Blue components)
			    - Last 2 digits: AA (Alpha channel for transparency)
			    
			    Format Breakdown:
			    - "#FFFFFF": Solid White color (Red=FF, Green=FF, Blue=FF)
			    - "00": Fully transparent Alpha channel (0% opacity)
			    
			    Use Cases:
			    - Hiding data labels when not needed
			    - Making chart backgrounds transparent
			    - Conditional formatting to show/hide elements based on business rules
			    - Creating invisible placeholders in visual layouts
			    
			    This measure returns a text value that can be used directly in
			    conditional formatting rules for font color, background color, etc.
			*/
			"#FFFFFF00"
			```
		displayFolder: other measures
		lineageTag: a80c7118-c786-4e08-a0fa-8d9d87f87fd7

	measure 'Current Time UTC' = ```
			
			/*
			    Business Goal: Returns the current date and time in UTC (Coordinated Universal Time) format.
			    This measure is volatile and refreshes with every visual interaction in the report.
			    It returns formatted text suitable for direct use in visualizations as a timestamp indicator.
			    
			    Important Note: This measure is recalculated every time the data model is refreshed
			    or when any visual interaction occurs, which may impact report performance in large models.
			*/
			VAR UTC_Timestamp =
			    /*
			        UTCNOW: Returns the current date and time in UTC (Coordinated Universal Time).
			        This function is volatile and returns a different value each time it's evaluated.
			        
			        TIME: Creates a time value from hours, minutes, and seconds.
			        Here, TIME(1,0,0) adds 1 hour to the UTC time. This appears to be adjusting
			        for a specific time zone offset (e.g., UTC+1 for Central European Time).
			        Note: If pure UTC is needed without offset, remove the TIME addition.
			    */
			    UTCNOW () + TIME ( 1, 0, 0 )
			VAR Formatted_Timestamp =
			    FORMAT (
			        UTC_Timestamp,
			        /*
			            FORMAT: Converts a value to text according to the specified format string.
			            "MM/dd/yyyy hh:mm:ss AM/PM" - American date/time format:
			            - "MM": Month as two digits (01-12)
			            - "dd": Day as two digits (01-31) 
			            - "yyyy": Four-digit year
			            - "hh": Hours in 12-hour format (01-12)
			            - "mm": Minutes (00-59)
			            - "ss": Seconds (00-59)
			            - "AM/PM": 12-hour clock period indicator
			            
			            For European format, use: "dd/MM/yyyy HH:mm:ss" (24-hour format)
			            For ISO format, use: "yyyy-MM-dd HH:mm:ss"
			        */
			        "MM/dd/yyyy hh:mm:ss AM/PM"
			    )
			RETURN
			    Formatted_Timestamp
			```
		displayFolder: other measures
		lineageTag: 20f55119-cdfa-4f58-977f-ddf76aadf00b

	measure 'Sales Selected Variable Optimized' =
			
			/*
			    Business Goal: This measure creates a comprehensive text label that combines:
			    1. A description of actively selected filters (Segment and Product)
			    2. Key performance indicators including:
			       - Percentage share of annual total sales
			       - Year-over-Year change with arrow symbol
			       - Previous year sales value
			       - Absolute YoY change in millions
			    The output format is: "Selected Segment: X / Selected Product: Y (↑ | PY: 1.50M | YoY: 0.25M | 15.25%)"
			    This provides complete context about both the filter selection and sales performance in a single text field.
			*/
			VAR _Segment =
			    /*
			        SELECTEDVALUE: Returns the value of the specified column when there's only one value
			        in the current filter context. If multiple values exist, returns BLANK().
			        This captures which Segment is currently selected in report filters/slicers.
			    */
			    SELECTEDVALUE ( financials[Segment] )
			VAR _Product =
			    /*
			        SELECTEDVALUE: Captures the currently selected Product from filters/slicers.
			        Used to build descriptive text about the current filter context.
			    */
			    SELECTEDVALUE ( financials[Product] )
			
			// 1. Performance Calculations (IFERROR Stabilization):
			VAR Current_Sales =
			    /*
			        IFERROR: Wraps the base Sales measure to handle any calculation errors gracefully.
			        Returns BLANK() instead of an error, making the measure more robust.
			    */
			    IFERROR ( [Sales], BLANK () )
			VAR Grand_Total_Sales_In_Year =
			    /*
			        CALCULATE with REMOVEFILTERS and ALL: Calculates the total Sales for the entire dataset.
			        - REMOVEFILTERS(financials): Removes all filters from the financials table
			        - ALL('Dates Optimized'): Removes all filters from the dates table
			        This gives the grand total Sales for context, used to calculate percentage share.
			    */
			    CALCULATE (
			        IFERROR ( [Sales], BLANK () ),
			        REMOVEFILTERS ( financials ),
			        ALL ( 'Dates Optimized' )
			    )
			VAR Previous_Year_Sales =
			    /*
			        CALCULATE with SAMEPERIODLASTYEAR: Calculates Sales for the same period in the previous year.
			        Standard time intelligence pattern for YoY comparisons.
			    */
			    CALCULATE (
			        IFERROR ( [Sales], BLANK () ),
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] )
			    )
			
			// 2. Change Calculations and Formatting
			VAR Share_Percentage =
			    /*
			        DIVIDE: Safely calculates the percentage share of current Sales relative to grand total.
			        Returns BLANK() if division by zero occurs.
			    */
			    DIVIDE ( Current_Sales, Grand_Total_Sales_In_Year, BLANK () )
			VAR YoY_Absolute_Change =
			    /*
			        COALESCE: Replaces BLANK values with 0 to ensure correct arithmetic operations.
			        Calculates the absolute change in Sales compared to previous year.
			    */
			    COALESCE ( Current_Sales, 0 ) - COALESCE ( Previous_Year_Sales, 0 )
			VAR YoY_Absolute_Change_Millions =
			    /*
			        DIVIDE: Converts the absolute change to millions for better readability.
			        Returns BLANK() if division fails.
			    */
			    DIVIDE ( YoY_Absolute_Change, 1000000, BLANK () )
			VAR Previous_Sales_Millions =
			    /*
			        DIVIDE: Converts previous year Sales to millions for consistent formatting.
			    */
			    DIVIDE ( Previous_Year_Sales, 1000000, BLANK () )
			
			// 3. Text Logic (Filters/Symbols):
			VAR Arrow_Symbol =
			    /*
			        Nested IF statements to determine the appropriate arrow symbol:
			        - Up arrow (↑) for increase in Sales (favorable)
			        - Down arrow (↓) for decrease in Sales (unfavorable)
			        - BLANK() for no change
			        Note: This correctly shows upward arrow for sales growth (positive change).
			    */
			    IF (
			        YoY_Absolute_Change > 0,
			        UNICHAR ( 11165 ), // Up arrow for sales increase (good)
			        IF ( YoY_Absolute_Change < 0, UNICHAR ( 11167 ), BLANK () ) // Down arrow or BLANK
			    )
			VAR Segment_Text_Fragment =
			    /*
			        ISFILTERED: Returns TRUE if the specified column has an active filter applied.
			        Creates text only when the Segment filter is actively used.
			    */
			    IF (
			        ISFILTERED ( financials[Segment] ),
			        "Selected Segment: " & _Segment,
			        BLANK ()
			    )
			VAR Product_Text_Fragment =
			    /*
			        ISFILTERED: Checks if Product column has active filters.
			        Creates descriptive text only when Product filter is applied.
			    */
			    IF (
			        ISFILTERED ( financials[Product] ),
			        "Selected Product: " & _Product,
			        BLANK ()
			    )
			VAR Separator_Text_Filter =
			    /*
			        AND with NOT ISBLANK: Adds a separator " / " only when both Segment and Product
			        have active filters and both text fragments are non-blank.
			    */
			    IF (
			        AND (
			            NOT ISBLANK ( Segment_Text_Fragment ),
			            NOT ISBLANK ( Product_Text_Fragment )
			        ),
			        " / ",
			        BLANK ()
			    )
			VAR Filter_Texts =
			    /*
			        TRIM and COALESCE: Combines all filter-related text fragments into a single string.
			        COALESCE replaces BLANK values with empty strings, then TRIM removes extra spaces.
			    */
			    TRIM (
			        COALESCE ( Segment_Text_Fragment, "" ) & COALESCE ( Separator_Text_Filter, "" )
			            & COALESCE ( Product_Text_Fragment, "" )
			    )
			
			// 4. Conditional KPI Text Creation (NO NOMINAL VALUE):
			// Element A: Symbol (first in sequence)
			VAR Arrow_Fragment =
			    COALESCE ( Arrow_Symbol, "" )
			// Element B: PY Value
			VAR PY_Fragment =
			    IF (
			        NOT ISBLANK ( Previous_Sales_Millions ),
			        "PY: " & FORMAT ( Previous_Sales_Millions, "#,##0.00" ) & "M",
			        BLANK ()
			    )
			// Element C: YoY Value
			VAR YoY_Fragment_Text =
			    IF (
			        NOT ISBLANK ( YoY_Absolute_Change_Millions ),
			        "YoY: " & FORMAT ( YoY_Absolute_Change_Millions, "#,##0.00" ) & "M",
			        BLANK ()
			    )
			// Element D: Share %
			VAR Share_Fragment =
			    IF (
			        NOT ISBLANK ( Share_Percentage ),
			        FORMAT ( Share_Percentage, "0.00%" ),
			        BLANK ()
			    )
			
			// Concatenating values in the parenthesis: (Symbol | PY | YoY | Share)
			VAR Inner_KPI_Text =
			    /*
			        Complex string concatenation with conditional separators.
			        Adds " | " separators only between non-blank elements to avoid
			        output like " |  | value" when some elements are missing.
			        This ensures clean output regardless of which metrics are available.
			    */
			    COALESCE ( Arrow_Fragment, "" )
			        & IF (
			            NOT ISBLANK ( Arrow_Fragment ) && NOT ISBLANK ( PY_Fragment ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( PY_Fragment, "" )
			        & IF (
			            NOT ISBLANK ( COALESCE ( Arrow_Fragment, PY_Fragment ) )
			                && NOT ISBLANK ( YoY_Fragment_Text ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( YoY_Fragment_Text, "" )
			        & IF (
			            NOT ISBLANK ( COALESCE ( Arrow_Fragment, PY_Fragment, YoY_Fragment_Text ) )
			                && NOT ISBLANK ( Share_Fragment ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( Share_Fragment, "" )
			
			VAR KPI_Text =
			    /*
			        Wraps the inner KPI text in parentheses, but only if there's current Sales data.
			        This ensures we don't show performance metrics when there's no underlying sales data.
			    */
			    IF ( NOT ISBLANK ( Current_Sales ), " (" & Inner_KPI_Text & ")", BLANK () )
			
			RETURN
			    /*
			        Final combination: Filter description text + KPI information in parentheses.
			        COALESCE ensures blank values are handled gracefully in the final string.
			        The result provides complete context about both what is being viewed (filters)
			        and how it's performing (KPI metrics).
			    */
			    COALESCE ( Filter_Texts, "" ) & COALESCE ( KPI_Text, "" )
		displayFolder: sales
		lineageTag: 2f6598a3-eb90-424a-b134-06350f857fca

	measure 'COGS Selected Variable Optimized' =
			
			/*
			    Business Goal: This measure creates a comprehensive text label that combines:
			    1. A description of actively selected filters (Segment and Product)
			    2. Key performance indicators including:
			       - Percentage share of annual total
			       - Year-over-Year change with arrow symbol
			       - Previous year value
			       - Absolute YoY change in millions
			    The output format is: "Selected Segment: X / Selected Product: Y (↑ | PY: 1.50M | YoY: 0.25M | 15.25%)"
			*/
			VAR _Segment =
			    /*
			        SELECTEDVALUE: Returns the value of the specified column when there's only one value
			        in the current filter context. If multiple values exist, returns BLANK().
			        This captures which Segment is currently selected in report filters/slicers.
			    */
			    SELECTEDVALUE ( financials[Segment] )
			VAR _Product =
			    /*
			        SELECTEDVALUE: Captures the currently selected Product from filters/slicers.
			        Used to build descriptive text about the current filter context.
			    */
			    SELECTEDVALUE ( financials[Product] )
			
			// 1. Performance Calculations (IFERROR Stabilization):
			VAR Current_COGS =
			    /*
			        IFERROR: Wraps the base COGS measure to handle any calculation errors gracefully.
			        Returns BLANK() instead of an error, making the measure more robust.
			    */
			    IFERROR ( [COGS], BLANK () )
			VAR Grand_Total_COGS_In_Year =
			    /*
			        CALCULATE with REMOVEFILTERS and ALL: Calculates the total COGS for the entire dataset.
			        - REMOVEFILTERS(financials): Removes all filters from the financials table
			        - ALL('Dates Optimized'): Removes all filters from the dates table
			        This gives the grand total COGS for context, used to calculate percentage share.
			    */
			    CALCULATE (
			        IFERROR ( [COGS], BLANK () ),
			        REMOVEFILTERS ( financials ),
			        ALL ( 'Dates Optimized' )
			    )
			VAR Previous_Year_COGS =
			    /*
			        CALCULATE with SAMEPERIODLASTYEAR: Calculates COGS for the same period in the previous year.
			        Standard time intelligence pattern for YoY comparisons.
			    */
			    CALCULATE (
			        IFERROR ( [COGS], BLANK () ),
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] )
			    )
			
			// 2. Change Calculations and Formatting
			VAR Share_Percentage =
			    /*
			        DIVIDE: Safely calculates the percentage share of current COGS relative to grand total.
			        Returns BLANK() if division by zero occurs.
			    */
			    DIVIDE ( Current_COGS, Grand_Total_COGS_In_Year, BLANK () )
			VAR YoY_Absolute_Change =
			    /*
			        COALESCE: Replaces BLANK values with 0 to ensure correct arithmetic operations.
			        Calculates the absolute change in COGS compared to previous year.
			    */
			    COALESCE ( Current_COGS, 0 ) - COALESCE ( Previous_Year_COGS, 0 )
			VAR YoY_Absolute_Change_Millions =
			    /*
			        DIVIDE: Converts the absolute change to millions for better readability.
			        Returns BLANK() if division fails.
			    */
			    DIVIDE ( YoY_Absolute_Change, 1000000, BLANK () )
			VAR Previous_COGS_Millions =
			    /*
			        DIVIDE: Converts previous year COGS to millions for consistent formatting.
			    */
			    DIVIDE ( Previous_Year_COGS, 1000000, BLANK () )
			
			// 3. Text Logic (Filters/Symbols):
			VAR Arrow_Symbol =
			    /*
			        Nested IF statements to determine the appropriate arrow symbol:
			        - Down arrow (↓) for decrease in COGS (favorable)
			        - Up arrow (↑) for increase in COGS (unfavorable)
			        - BLANK() for no change
			    */
			    IF (
			        YoY_Absolute_Change < 0,
			        UNICHAR ( 11167 ), // Down arrow
			        IF ( YoY_Absolute_Change > 0, UNICHAR ( 11165 ), BLANK () ) // Up arrow or BLANK
			    )
			VAR Segment_Text_Fragment =
			    /*
			        ISFILTERED: Returns TRUE if the specified column has an active filter applied.
			        Creates text only when the Segment filter is actively used.
			    */
			    IF (
			        ISFILTERED ( financials[Segment] ),
			        "Selected Segment: " & _Segment,
			        BLANK ()
			    )
			VAR Product_Text_Fragment =
			    /*
			        ISFILTERED: Checks if Product column has active filters.
			        Creates descriptive text only when Product filter is applied.
			    */
			    IF (
			        ISFILTERED ( financials[Product] ),
			        "Selected Product: " & _Product,
			        BLANK ()
			    )
			VAR Separator_Text_Filter =
			    /*
			        AND with NOT ISBLANK: Adds a separator " / " only when both Segment and Product
			        have active filters and both text fragments are non-blank.
			    */
			    IF (
			        AND (
			            NOT ISBLANK ( Segment_Text_Fragment ),
			            NOT ISBLANK ( Product_Text_Fragment )
			        ),
			        " / ",
			        BLANK ()
			    )
			VAR Filter_Texts =
			    /*
			        TRIM and COALESCE: Combines all filter-related text fragments into a single string.
			        COALESCE replaces BLANK values with empty strings, then TRIM removes extra spaces.
			    */
			    TRIM (
			        COALESCE ( Segment_Text_Fragment, "" ) & COALESCE ( Separator_Text_Filter, "" )
			            & COALESCE ( Product_Text_Fragment, "" )
			    )
			
			// 4. Conditional KPI Text Creation (NO NOMINAL VALUE):
			// Element A: Symbol (first in sequence)
			VAR Arrow_Fragment =
			    COALESCE ( Arrow_Symbol, "" )
			// Element B: PY Value
			VAR PY_Fragment =
			    IF (
			        NOT ISBLANK ( Previous_COGS_Millions ),
			        "PY: " & FORMAT ( Previous_COGS_Millions, "#,##0.00" ) & "M",
			        BLANK ()
			    )
			// Element C: YoY Value
			VAR YoY_Fragment_Text =
			    IF (
			        NOT ISBLANK ( YoY_Absolute_Change_Millions ),
			        "YoY: " & FORMAT ( YoY_Absolute_Change_Millions, "#,##0.00" ) & "M",
			        BLANK ()
			    )
			// Element D: Share %
			VAR Share_Fragment =
			    IF (
			        NOT ISBLANK ( Share_Percentage ),
			        FORMAT ( Share_Percentage, "0.00%" ),
			        BLANK ()
			    )
			
			// Concatenating values in the parenthesis: (Symbol | PY | YoY | Share)
			VAR Inner_KPI_Text =
			    /*
			        Complex string concatenation with conditional separators.
			        Adds " | " separators only between non-blank elements to avoid
			        output like " |  | value" when some elements are missing.
			    */
			    COALESCE ( Arrow_Fragment, "" )
			        & IF (
			            NOT ISBLANK ( Arrow_Fragment ) && NOT ISBLANK ( PY_Fragment ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( PY_Fragment, "" )
			        & IF (
			            NOT ISBLANK ( COALESCE ( Arrow_Fragment, PY_Fragment ) )
			                && NOT ISBLANK ( YoY_Fragment_Text ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( YoY_Fragment_Text, "" )
			        & IF (
			            NOT ISBLANK ( COALESCE ( Arrow_Fragment, PY_Fragment, YoY_Fragment_Text ) )
			                && NOT ISBLANK ( Share_Fragment ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( Share_Fragment, "" )
			
			VAR KPI_Text =
			    /*
			        Wraps the inner KPI text in parentheses, but only if there's current COGS data.
			    */
			    IF ( NOT ISBLANK ( Current_COGS ), " (" & Inner_KPI_Text & ")", BLANK () )
			
			RETURN
			    /*
			        Final combination: Filter description text + KPI information in parentheses.
			        COALESCE ensures blank values are handled gracefully in the final string.
			    */
			    COALESCE ( Filter_Texts, "" ) & COALESCE ( KPI_Text, "" )
		displayFolder: cogs
		lineageTag: 712cd02a-5c86-46bb-a7dd-cbf05ad0b242

	measure 'Profit Selected Variable Optimized' =
			
			/*
			    Business Goal: This measure creates a comprehensive text label that combines:
			    1. A description of actively selected filters (Segment and Product)
			    2. Key performance indicators including:
			       - Percentage share of annual total profit
			       - Year-over-Year change with arrow symbol
			       - Previous year profit value
			       - Absolute YoY change in millions
			    The output format is: "Selected Segment: X / Selected Product: Y (↑ | PY: 1.50M | YoY: 0.25M | 15.25%)"
			    This provides complete context about both the filter selection and profit performance in a single text field.
			*/
			VAR _Segment =
			    /*
			        SELECTEDVALUE: Returns the value of the specified column when there's only one value
			        in the current filter context. If multiple values exist, returns BLANK().
			        This captures which Segment is currently selected in report filters/slicers.
			    */
			    SELECTEDVALUE ( financials[Segment] )
			VAR _Product =
			    /*
			        SELECTEDVALUE: Captures the currently selected Product from filters/slicers.
			        Used to build descriptive text about the current filter context.
			    */
			    SELECTEDVALUE ( financials[Product] )
			
			// 1. Performance Calculations (IFERROR Stabilization):
			VAR Current_Profit =
			    /*
			        IFERROR: Wraps the base Profit measure to handle any calculation errors gracefully.
			        Returns BLANK() instead of an error, making the measure more robust.
			    */
			    IFERROR ( [Profit], BLANK () )
			VAR Grand_Total_Profit_In_Year =
			    /*
			        CALCULATE with REMOVEFILTERS and ALL: Calculates the total Profit for the entire dataset.
			        - REMOVEFILTERS(financials): Removes all filters from the financials table
			        - ALL('Dates Optimized'): Removes all filters from the dates table
			        This gives the grand total Profit for context, used to calculate percentage share.
			    */
			    CALCULATE (
			        IFERROR ( [Profit], BLANK () ),
			        REMOVEFILTERS ( financials ),
			        ALL ( 'Dates Optimized' )
			    )
			VAR Previous_Year_Profit =
			    /*
			        CALCULATE with SAMEPERIODLASTYEAR: Calculates Profit for the same period in the previous year.
			        Standard time intelligence pattern for YoY comparisons.
			    */
			    CALCULATE (
			        IFERROR ( [Profit], BLANK () ),
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] )
			    )
			
			// 2. Change Calculations and Formatting
			VAR Share_Percentage =
			    /*
			        DIVIDE: Safely calculates the percentage share of current Profit relative to grand total.
			        Returns BLANK() if division by zero occurs.
			    */
			    DIVIDE ( Current_Profit, Grand_Total_Profit_In_Year, BLANK () )
			VAR YoY_Absolute_Change =
			    /*
			        COALESCE: Replaces BLANK values with 0 to ensure correct arithmetic operations.
			        Calculates the absolute change in Profit compared to previous year.
			    */
			    COALESCE ( Current_Profit, 0 ) - COALESCE ( Previous_Year_Profit, 0 )
			VAR YoY_Absolute_Change_Millions =
			    /*
			        DIVIDE: Converts the absolute change to millions for better readability.
			        Returns BLANK() if division fails.
			    */
			    DIVIDE ( YoY_Absolute_Change, 1000000, BLANK () )
			VAR Previous_Profit_Millions =
			    /*
			        DIVIDE: Converts previous year Profit to millions for consistent formatting.
			    */
			    DIVIDE ( Previous_Year_Profit, 1000000, BLANK () )
			
			// 3. Text Logic (Filters/Symbols):
			VAR Arrow_Symbol =
			    /*
			        Nested IF statements to determine the appropriate arrow symbol:
			        - Up arrow (↑) for increase in Profit (favorable)
			        - Down arrow (↓) for decrease in Profit (unfavorable)
			        - BLANK() for no change
			        Note: This correctly shows upward arrow for profit growth (positive change).
			    */
			    IF (
			        YoY_Absolute_Change > 0,
			        UNICHAR ( 11165 ), // Up arrow for profit increase (good)
			        IF ( YoY_Absolute_Change < 0, UNICHAR ( 11167 ), BLANK () ) // Down arrow or BLANK
			    )
			VAR Segment_Text_Fragment =
			    /*
			        ISFILTERED: Returns TRUE if the specified column has an active filter applied.
			        Creates text only when the Segment filter is actively used.
			    */
			    IF (
			        ISFILTERED ( financials[Segment] ),
			        "Selected Segment: " & _Segment,
			        BLANK ()
			    )
			VAR Product_Text_Fragment =
			    /*
			        ISFILTERED: Checks if Product column has active filters.
			        Creates descriptive text only when Product filter is applied.
			    */
			    IF (
			        ISFILTERED ( financials[Product] ),
			        "Selected Product: " & _Product,
			        BLANK ()
			    )
			VAR Separator_Text_Filter =
			    /*
			        AND with NOT ISBLANK: Adds a separator " / " only when both Segment and Product
			        have active filters and both text fragments are non-blank.
			    */
			    IF (
			        AND (
			            NOT ISBLANK ( Segment_Text_Fragment ),
			            NOT ISBLANK ( Product_Text_Fragment )
			        ),
			        " / ",
			        BLANK ()
			    )
			VAR Filter_Texts =
			    /*
			        TRIM and COALESCE: Combines all filter-related text fragments into a single string.
			        COALESCE replaces BLANK values with empty strings, then TRIM removes extra spaces.
			    */
			    TRIM (
			        COALESCE ( Segment_Text_Fragment, "" ) & COALESCE ( Separator_Text_Filter, "" )
			            & COALESCE ( Product_Text_Fragment, "" )
			    )
			
			// 4. Conditional KPI Text Creation (NO NOMINAL VALUE):
			// Element A: Symbol (first in sequence)
			VAR Arrow_Fragment =
			    COALESCE ( Arrow_Symbol, "" )
			// Element B: PY Value
			VAR PY_Fragment =
			    IF (
			        NOT ISBLANK ( Previous_Profit_Millions ),
			        "PY: " & FORMAT ( Previous_Profit_Millions, "#,##0.00" ) & "M",
			        BLANK ()
			    )
			// Element C: YoY Value
			VAR YoY_Fragment_Text =
			    IF (
			        NOT ISBLANK ( YoY_Absolute_Change_Millions ),
			        "YoY: " & FORMAT ( YoY_Absolute_Change_Millions, "#,##0.00" ) & "M",
			        BLANK ()
			    )
			// Element D: Share %
			VAR Share_Fragment =
			    IF (
			        NOT ISBLANK ( Share_Percentage ),
			        FORMAT ( Share_Percentage, "0.00%" ),
			        BLANK ()
			    )
			
			// Concatenating values in the parenthesis: (Symbol | PY | YoY | Share)
			VAR Inner_KPI_Text =
			    /*
			        Complex string concatenation with conditional separators.
			        Adds " | " separators only between non-blank elements to avoid
			        output like " |  | value" when some elements are missing.
			        This ensures clean output regardless of which metrics are available.
			    */
			    COALESCE ( Arrow_Fragment, "" )
			        & IF (
			            NOT ISBLANK ( Arrow_Fragment ) && NOT ISBLANK ( PY_Fragment ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( PY_Fragment, "" )
			        & IF (
			            NOT ISBLANK ( COALESCE ( Arrow_Fragment, PY_Fragment ) )
			                && NOT ISBLANK ( YoY_Fragment_Text ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( YoY_Fragment_Text, "" )
			        & IF (
			            NOT ISBLANK ( COALESCE ( Arrow_Fragment, PY_Fragment, YoY_Fragment_Text ) )
			                && NOT ISBLANK ( Share_Fragment ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( Share_Fragment, "" )
			
			VAR KPI_Text =
			    /*
			        Wraps the inner KPI text in parentheses, but only if there's current Profit data.
			        This ensures we don't show performance metrics when there's no underlying profit data.
			    */
			    IF ( NOT ISBLANK ( Current_Profit ), " (" & Inner_KPI_Text & ")", BLANK () )
			
			RETURN
			    /*
			        Final combination: Filter description text + KPI information in parentheses.
			        COALESCE ensures blank values are handled gracefully in the final string.
			        The result provides complete context about both what is being viewed (filters)
			        and how it's performing (KPI metrics).
			    */
			    COALESCE ( Filter_Texts, "" ) & COALESCE ( KPI_Text, "" )
		displayFolder: profit
		lineageTag: c4995597-851c-4da0-bb41-03f8b5c4eedd

	measure 'Units Sold Selected Variable Optimized' =
			
			/*
			    Business Goal: This measure creates a comprehensive text label that combines:
			    1. A description of actively selected filters (Segment and Product)
			    2. Key performance indicators for sales volume including:
			       - Percentage share of annual total units sold
			       - Year-over-Year change with arrow symbol
			       - Previous year units sold value
			       - Absolute YoY change in millions of units
			    The output format is: "Selected Segment: X / Selected Product: Y (↑ | PY: 1.50M | YoY: 0.25M | 15.25%)"
			    This provides complete context about both the filter selection and sales volume performance in a single text field.
			*/
			VAR _Segment =
			    /*
			        SELECTEDVALUE: Returns the value of the specified column when there's only one value
			        in the current filter context. If multiple values exist, returns BLANK().
			        This captures which Segment is currently selected in report filters/slicers.
			    */
			    SELECTEDVALUE ( financials[Segment] )
			VAR _Product =
			    /*
			        SELECTEDVALUE: Captures the currently selected Product from filters/slicers.
			        Used to build descriptive text about the current filter context.
			    */
			    SELECTEDVALUE ( financials[Product] )
			
			// 1. Performance Calculations (IFERROR Stabilization):
			VAR Current_Units_Sold =
			    /*
			        IFERROR: Wraps the base Units Sold measure to handle any calculation errors gracefully.
			        Returns BLANK() instead of an error, making the measure more robust.
			    */
			    IFERROR ( [Units Sold], BLANK () )
			VAR Grand_Total_Units_Sold_In_Year =
			    /*
			        CALCULATE with REMOVEFILTERS and ALL: Calculates the total Units Sold for the entire dataset.
			        - REMOVEFILTERS(financials): Removes all filters from the financials table
			        - ALL('Dates Optimized'): Removes all filters from the dates table
			        This gives the grand total Units Sold for context, used to calculate percentage share.
			    */
			    CALCULATE (
			        IFERROR ( [Units Sold], BLANK () ),
			        REMOVEFILTERS ( financials ),
			        ALL ( 'Dates Optimized' )
			    )
			VAR Previous_Year_Units_Sold =
			    /*
			        CALCULATE with SAMEPERIODLASTYEAR: Calculates Units Sold for the same period in the previous year.
			        Standard time intelligence pattern for YoY volume comparisons.
			    */
			    CALCULATE (
			        IFERROR ( [Units Sold], BLANK () ),
			        SAMEPERIODLASTYEAR ( 'Dates Optimized'[Date] )
			    )
			
			// 2. Change Calculations and Formatting
			VAR Share_Percentage =
			    /*
			        DIVIDE: Safely calculates the percentage share of current Units Sold relative to grand total.
			        Returns BLANK() if division by zero occurs.
			    */
			    DIVIDE ( Current_Units_Sold, Grand_Total_Units_Sold_In_Year, BLANK () )
			VAR YoY_Absolute_Change =
			    /*
			        COALESCE: Replaces BLANK values with 0 to ensure correct arithmetic operations.
			        Calculates the absolute change in Units Sold compared to previous year.
			    */
			    COALESCE ( Current_Units_Sold, 0 ) - COALESCE ( Previous_Year_Units_Sold, 0 )
			VAR YoY_Absolute_Change_Millions =
			    /*
			        DIVIDE: Converts the absolute change to millions for better readability.
			        Returns BLANK() if division fails.
			    */
			    DIVIDE ( YoY_Absolute_Change, 1000000, BLANK () )
			VAR Previous_Units_Sold_Millions =
			    /*
			        DIVIDE: Converts previous year Units Sold to millions for consistent formatting.
			    */
			    DIVIDE ( Previous_Year_Units_Sold, 1000000, BLANK () )
			
			// 3. Text Logic (Filters/Symbols):
			VAR Arrow_Symbol =
			    /*
			        Nested IF statements to determine the appropriate arrow symbol:
			        - Up arrow (↑) for increase in Units Sold (favorable)
			        - Down arrow (↓) for decrease in Units Sold (unfavorable)
			        - BLANK() for no change
			        Note: This correctly shows upward arrow for volume growth (positive change).
			    */
			    IF (
			        YoY_Absolute_Change > 0,
			        UNICHAR ( 11165 ), // Up arrow for volume increase (good)
			        IF ( YoY_Absolute_Change < 0, UNICHAR ( 11167 ), BLANK () ) // Down arrow or BLANK
			    )
			VAR Segment_Text_Fragment =
			    /*
			        ISFILTERED: Returns TRUE if the specified column has an active filter applied.
			        Creates text only when the Segment filter is actively used.
			    */
			    IF (
			        ISFILTERED ( financials[Segment] ),
			        "Selected Segment: " & _Segment,
			        BLANK ()
			    )
			VAR Product_Text_Fragment =
			    /*
			        ISFILTERED: Checks if Product column has active filters.
			        Creates descriptive text only when Product filter is applied.
			    */
			    IF (
			        ISFILTERED ( financials[Product] ),
			        "Selected Product: " & _Product,
			        BLANK ()
			    )
			VAR Separator_Text_Filter =
			    /*
			        AND with NOT ISBLANK: Adds a separator " / " only when both Segment and Product
			        have active filters and both text fragments are non-blank.
			    */
			    IF (
			        AND (
			            NOT ISBLANK ( Segment_Text_Fragment ),
			            NOT ISBLANK ( Product_Text_Fragment )
			        ),
			        " / ",
			        BLANK ()
			    )
			VAR Filter_Texts =
			    /*
			        TRIM and COALESCE: Combines all filter-related text fragments into a single string.
			        COALESCE replaces BLANK values with empty strings, then TRIM removes extra spaces.
			    */
			    TRIM (
			        COALESCE ( Segment_Text_Fragment, "" ) & COALESCE ( Separator_Text_Filter, "" )
			            & COALESCE ( Product_Text_Fragment, "" )
			    )
			
			// 4. Conditional KPI Text Creation (NO NOMINAL VALUE):
			// Element A: Symbol (first in sequence)
			VAR Arrow_Fragment =
			    COALESCE ( Arrow_Symbol, "" )
			// Element B: PY Value
			VAR PY_Fragment =
			    IF (
			        NOT ISBLANK ( Previous_Units_Sold_Millions ),
			        "PY: " & FORMAT ( Previous_Units_Sold_Millions, "#,##0.00" ) & "M",
			        BLANK ()
			    )
			// Element C: YoY Value
			VAR YoY_Fragment_Text =
			    IF (
			        NOT ISBLANK ( YoY_Absolute_Change_Millions ),
			        "YoY: " & FORMAT ( YoY_Absolute_Change_Millions, "#,##0.00" ) & "M",
			        BLANK ()
			    )
			// Element D: Share %
			VAR Share_Fragment =
			    IF (
			        NOT ISBLANK ( Share_Percentage ),
			        FORMAT ( Share_Percentage, "0.00%" ),
			        BLANK ()
			    )
			
			// Concatenating values in the parenthesis: (Symbol | PY | YoY | Share)
			VAR Inner_KPI_Text =
			    /*
			        Complex string concatenation with conditional separators.
			        Adds " | " separators only between non-blank elements to avoid
			        output like " |  | value" when some elements are missing.
			        This ensures clean output regardless of which metrics are available.
			    */
			    COALESCE ( Arrow_Fragment, "" )
			        & IF (
			            NOT ISBLANK ( Arrow_Fragment ) && NOT ISBLANK ( PY_Fragment ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( PY_Fragment, "" )
			        & IF (
			            NOT ISBLANK ( COALESCE ( Arrow_Fragment, PY_Fragment ) )
			                && NOT ISBLANK ( YoY_Fragment_Text ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( YoY_Fragment_Text, "" )
			        & IF (
			            NOT ISBLANK ( COALESCE ( Arrow_Fragment, PY_Fragment, YoY_Fragment_Text ) )
			                && NOT ISBLANK ( Share_Fragment ),
			            " | ",
			            BLANK ()
			        )
			        & COALESCE ( Share_Fragment, "" )
			
			VAR KPI_Text =
			    /*
			        Wraps the inner KPI text in parentheses, but only if there's current Units Sold data.
			        This ensures we don't show performance metrics when there's no underlying volume data.
			    */
			    IF ( NOT ISBLANK ( Current_Units_Sold ), " (" & Inner_KPI_Text & ")", BLANK () )
			
			RETURN
			    /*
			        Final combination: Filter description text + KPI information in parentheses.
			        COALESCE ensures blank values are handled gracefully in the final string.
			        The result provides complete context about both what is being viewed (filters)
			        and how it's performing (KPI metrics for sales volume).
			    */
			    COALESCE ( Filter_Texts, "" ) & COALESCE ( KPI_Text, "" )
		displayFolder: units sold
		lineageTag: f67521f2-267f-4349-abd9-746c50c3e94d

	measure DumpFilters = ```
			
			VAR MaxFilters = 3
			RETURN
			"DumpFilters: " &
			IF ( 
			    ISFILTERED ( 'Dates Optimized'[Date] ), 
			    VAR ___f = FILTERS ( 'Dates Optimized'[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'Dates Optimized'[Date] )
			    VAR ___d = CONCATENATEX ( ___t, 'Dates Optimized'[Date], ", " )
			    VAR ___x = "'Dates Optimized'[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'Dates Optimized'[Month] ), 
			    VAR ___f = FILTERS ( 'Dates Optimized'[Month] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'Dates Optimized'[Month] )
			    VAR ___d = CONCATENATEX ( ___t, 'Dates Optimized'[Month], ", " )
			    VAR ___x = "'Dates Optimized'[Month] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'Dates Optimized'[Month Name] ), 
			    VAR ___f = FILTERS ( 'Dates Optimized'[Month Name] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'Dates Optimized'[Month Name] )
			    VAR ___d = CONCATENATEX ( ___t, 'Dates Optimized'[Month Name], ", " )
			    VAR ___x = "'Dates Optimized'[Month Name] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'Dates Optimized'[Month Name Full] ), 
			    VAR ___f = FILTERS ( 'Dates Optimized'[Month Name Full] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'Dates Optimized'[Month Name Full] )
			    VAR ___d = CONCATENATEX ( ___t, 'Dates Optimized'[Month Name Full], ", " )
			    VAR ___x = "'Dates Optimized'[Month Name Full] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'Dates Optimized'[Quarter] ), 
			    VAR ___f = FILTERS ( 'Dates Optimized'[Quarter] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'Dates Optimized'[Quarter] )
			    VAR ___d = CONCATENATEX ( ___t, 'Dates Optimized'[Quarter], ", " )
			    VAR ___x = "'Dates Optimized'[Quarter] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'Dates Optimized'[Year] ), 
			    VAR ___f = FILTERS ( 'Dates Optimized'[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'Dates Optimized'[Year] )
			    VAR ___d = CONCATENATEX ( ___t, 'Dates Optimized'[Year], ", " )
			    VAR ___x = "'Dates Optimized'[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( 'Dates Optimized'[YearMonthKey] ), 
			    VAR ___f = FILTERS ( 'Dates Optimized'[YearMonthKey] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, 'Dates Optimized'[YearMonthKey] )
			    VAR ___d = CONCATENATEX ( ___t, 'Dates Optimized'[YearMonthKey], ", " )
			    VAR ___x = "'Dates Optimized'[YearMonthKey] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[COGS] ), 
			    VAR ___f = FILTERS ( financials[COGS] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[COGS] )
			    VAR ___d = CONCATENATEX ( ___t, financials[COGS], ", " )
			    VAR ___x = "financials[COGS] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Country] ), 
			    VAR ___f = FILTERS ( financials[Country] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Country] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Country], ", " )
			    VAR ___x = "financials[Country] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Date] ), 
			    VAR ___f = FILTERS ( financials[Date] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Date] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Date], ", " )
			    VAR ___x = "financials[Date] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Discount Band] ), 
			    VAR ___f = FILTERS ( financials[Discount Band] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Discount Band] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Discount Band], ", " )
			    VAR ___x = "financials[Discount Band] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Discounts] ), 
			    VAR ___f = FILTERS ( financials[Discounts] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Discounts] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Discounts], ", " )
			    VAR ___x = "financials[Discounts] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Gross Sales] ), 
			    VAR ___f = FILTERS ( financials[Gross Sales] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Gross Sales] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Gross Sales], ", " )
			    VAR ___x = "financials[Gross Sales] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Manufacturing Price] ), 
			    VAR ___f = FILTERS ( financials[Manufacturing Price] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Manufacturing Price] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Manufacturing Price], ", " )
			    VAR ___x = "financials[Manufacturing Price] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Month Name] ), 
			    VAR ___f = FILTERS ( financials[Month Name] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Month Name] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Month Name], ", " )
			    VAR ___x = "financials[Month Name] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Month Number] ), 
			    VAR ___f = FILTERS ( financials[Month Number] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Month Number] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Month Number], ", " )
			    VAR ___x = "financials[Month Number] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Product] ), 
			    VAR ___f = FILTERS ( financials[Product] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Product] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Product], ", " )
			    VAR ___x = "financials[Product] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Profit] ), 
			    VAR ___f = FILTERS ( financials[Profit] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Profit] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Profit], ", " )
			    VAR ___x = "financials[Profit] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Sale Price] ), 
			    VAR ___f = FILTERS ( financials[Sale Price] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Sale Price] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Sale Price], ", " )
			    VAR ___x = "financials[Sale Price] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Sales] ), 
			    VAR ___f = FILTERS ( financials[Sales] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Sales] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Sales], ", " )
			    VAR ___x = "financials[Sales] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Segment] ), 
			    VAR ___f = FILTERS ( financials[Segment] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Segment] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Segment], ", " )
			    VAR ___x = "financials[Segment] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Units Sold] ), 
			    VAR ___f = FILTERS ( financials[Units Sold] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Units Sold] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Units Sold], ", " )
			    VAR ___x = "financials[Units Sold] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( financials[Year] ), 
			    VAR ___f = FILTERS ( financials[Year] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, financials[Year] )
			    VAR ___d = CONCATENATEX ( ___t, financials[Year], ", " )
			    VAR ___x = "financials[Year] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			 & IF ( 
			    ISFILTERED ( Model_Measures[Value] ), 
			    VAR ___f = FILTERS ( Model_Measures[Value] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( MaxFilters, ___f, Model_Measures[Value] )
			    VAR ___d = CONCATENATEX ( ___t, Model_Measures[Value], ", " )
			    VAR ___x = "Model_Measures[Value] = " & ___d & IF(___r > MaxFilters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x & UNICHAR(13) & UNICHAR(10)
			)
			---- MODEL MEASURES END ----
			
			
			```
		displayFolder: other measures
		lineageTag: 62b58e6e-2bda-420d-afcb-07cc274f3696

	column Value
		isHidden
		lineageTag: 880c39b9-c918-4b8d-8ad7-5bb699168901
		summarizeBy: none
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition Model_Measures = calculated
		mode: import
		source =
				
				/*
				    Business Goal: This appears to be a placeholder or structural measure that returns
				    an empty text value. It's likely used for one of the following purposes:
				    - As a placeholder during measure development
				    - For creating empty calculation groups
				    - As a base for dynamic measure selection
				    - For testing or structural purposes in the data model
				
				    Technical Note: The curly braces {} indicate this is returning a table with
				    a single row containing an empty text value, rather than a scalar value.
				    This syntax creates a single-column table with one empty string row.
				
				    Current implementation returns an empty table with one empty string cell.
				*/
				{ "" }

	annotation PBI_Id = 0b2e077d6552498f9b864a48d4bab438

